### ISSUE TITLE
Exception when decoding fail.

### ISSUE THREAD

**Issue by crakjie** [jilen/play-circe#11]
I got this obscure exception when the decoding is not possible ( in this case cause there is a laking field)

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[anon$2: Attempt to decode value on failed cursor: El(DownField(noscript),false,false)]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
    at scala.concurrent.Promise$class.complete(Promise.scala:55)
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: io.circe.DecodingFailure$$anon$2: Attempt to decode value on failed cursor: El(DownField(noscript),false,false)

```

The parsing code

```
Action.async(circe.json[String => Site])  ...
```

**Comment by djx314** [comment]
Do you mean
```scala
Action.async(circe.json[Site])
```
?

**Comment by crakjie** [comment]
No `[String => Site]` that allow a field to be provided after the parsing.
Exemple : 
you have a CRUD, the Update need the ID , but the Create don't need an id because it the server which create the ID. so you Create (post) is `Action.async(circe.json[String => Site])` and in your Update (put) `Action.async(circe.json[Site])`

But I have the same exception with `Action.async(circe.json[Site])`

**Comment by djx314** [comment]
circe maybe hasn't a Decoder[String => Site] because it's not a json.
Maybe you can show what json data you push to the play.

**Comment by crakjie** [comment]
I have the Decoder[String => Site] 
And as I said even when I use Decoder[Site] there is an exception.

**Comment by djx314** [comment]
What data do you post from the browser?

**Comment by crakjie** [comment]
```Jon
{
	"customer": "tutu",
	"site": "jacky & mickel",
	"siteUrl": "www.jacky-et-michel.com",
	"doCollect": true,
	"status": "ACTIVATED",
	"tagInit": "",
	"tagRun": "",
	//"noscript" : "" remove to see how the api react to error
}
```

Is the projet compliante with Play 2.5.8 ?

**Comment by djx314** [comment]
If you remove field "noscript", you must defined Option[String]
case class Site(
...
...
noscript: Option[String]
)
In your case class code. Because circe and other scala json lib will not convert null to not null field.

**Comment by crakjie** [comment]
Yes of course.
But if my user make an error and remove noscript, I'm not expecting a 500 error caused by an exception. But a 400 with some thing like the circe `DecodingFailure.message`

**Comment by djx314** [comment]
Yes, I think so. Mybe we can discuss this with @jilen

**Comment by Taig** [comment]
How does play-json handle this? I didn't give it a try, but I think I remember that this is the actual default behavior for decoding errors. To avoid that, you'd have to parse JSON (`Action(circe.json)`), and then in your controller logic decode to your `T` and handle decoding failures the way you want.

**Comment by crakjie** [comment]
@Taig It's what I'm doing in my controller.

**Comment by git4sun** [comment]
It is possible to add default values or function to handle the null cases in circe? Most of the cases I encountered could be easily handled by a default value or try catch value since scala always returns a value.
