### ISSUE TITLE
Logger class conflicts with any other defined Logger class in 2814.1

### ISSUE THREAD

**Issue by david-doyle-as24** [jilen/play-circe#81]
Upon upgrading from play-circe 2812.0 to 2814.1, the following code generates the following error:

CODE: 

import play.api.libs.circe.Circe
import play.api.mvc.{AbstractController, Action, AnyContent, ControllerComponents, Result, Results}
import javax.inject.Inject
import com.typesafe.scalalogging.StrictLogging
import scala.concurrent.ExecutionContext

class SampleController @Inject() (
    cc: ControllerComponents,
)(implicit ec: ExecutionContext)
    extends AbstractController(cc)
    with StrictLogging
    with Circe {
}

ERROR:

class SampleController inherits conflicting members:
protected val logger: com.typesafe.scalalogging.Logger (defined in trait StrictLogging) and
protected val logger: play.api.Logger (defined in trait Logging)
  (note: this can be resolved by declaring an `override` in class ListingsController.)]
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
        at scala.Option.map(Option.scala:230)
        at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$1(PlayReload.scala:42)
        at scala.Option.map(Option.scala:230)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:37)
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:30)
        at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:65)
        at scala.util.Either$LeftProjection.map(Either.scala:573)
        at play.sbt.run.PlayReload$.compile(PlayReload.scala:65)

**Comment by jilen** [comment]
Hm. seems you have to chose `play.api.Logging` currently. May be an injectable `BodyParsers` can help there.
